pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: test
  jobs:
  - job: 'pytest'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - script: |
        pip install -r test/requirements.txt
        pytest
- stage: documentation
  jobs:
  - job: documentation
    steps:
    - script: |
        sudo apt-get install doxygen
        doxygen Doxyfile
- stage: format
  jobs:
  - job: format
    steps:
    - script: |
        scripts/format
        scripts/git-diff
