pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: test
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pip install -r test/requirements.txt
      pytest
    displayName: 'pytest'
- job: documentation
  steps:
  - script: |
      sudo apt-get install doxygen
      doxygen Doxyfile
    displayName: 'documentation'
- job: format
  steps:
  - script: |
      scripts/format
      scripts/git-diff
    displayName: 'format'