language: python
os: linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
  - ${CC} --version
  - ${CXX} --version
  - cmake --version
  - pip install -r test/requirements.txt
install:
  - mkdir build
  - cd build
  - cmake ../ -DINSTALL_TESTS=ON -DCMAKE_CXX_COMPILER=${CXX}
  - cmake --build . --target install
  - cd ..
script: pytest -v

jobs:
  include:
    - name: "Python 3.6"
      python: 3.6
    - name: "Python 3.7"
      python: 3.7
    - name: "Python 3.8"
      python: 3.8
    - stage: documentation
      branches:
        only:
          - master
          - /devel.*/
          - /doc.*/
      before_install:
        - sudo apt-get install -y doxygen
      install: " "
      script:
        - doxygen Doxyfile
    - stage: format
      branches:
        only:
          - master
          - /devel.*/
      before_install:
        - sudo apt-get install -y clang-format
      install: " "
      script:
        - scripts/format
        - scripts/git-diff
