language: python

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install -r test/requirements.txt

install:
  - cmake -B build
  - cmake --build build --target install -DINSTALL_TESTS=ON

script:
  - pytest -v
