trigger:
  branches:
    include:
      - master
      - devel
      - azure-pipelines
stages:
- stage: test
  jobs:
  - job: 'pytest'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Test with python version $(python.version)'
    - script: |
        python -m pip install --upgrade pip
        cd pyebi
      displayName: 'Upgrade pip'
    - script: |
        pip install -r requirements.txt
        pip install -r test/requirements.txt
      displayName: 'Install dependencies'
    - script: pip install .
      displayName: 'Install package'
    - script: pytest
      displayName: 'Run tests'
- stage: documentation
  jobs:
  - job: documentation
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sudo apt-get install -y doxygen
        doxygen Doxyfile
      displayName: 'Build documentation'
- stage: format
  jobs:
  - job: format
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sudo apt-get install -y clang-format
        scripts/format
        scripts/git-diff
      displayName: 'Check format'
